export const MUSHROOM_COMMON_NAMES = [
  'Horse Mushroom',
  'The Prince',
  'Salt-loving Agaricus',
  'Meadow Mushroom',
  'Wood Mushroom',
  'Yellow Stainer',
  'Common Fieldcap',
  'Spring Fieldcap',
  'Fused Polypore',
  'Sheep Polypore',
  'Orange Peel Fungus',
  'Banded Amanita',
  'Eastern destroying angel',
  'Solitary Lepidella',
  'Tawny grisette',
  "Jackson's slender amanita",
  'Fly Amanita',
  'Panther Amanita',
  'Peach-Colored Fly Agaric',
  'Death Cap Amanita',
  'Grey veiled amanita',
  'Royal Fly Agaric',
  'Blushing Amanita',
  'Olive Amanita',
  'Grisette',
  'Destroying angel',
  'Club Foot',
  'Northern Honey Fungus',
  'Bulbous Honey Fungus',
  'Honey Mushroom',
  'Long-stemmed Bolete',
  'Jelly Ear Fungus',
  'Pinecone Tooth',
  'Blushing Flagrant Tooth',
  'Two-colored bolete',
  'Yellow Fieldcap',
  'King Bolete',
  'Pinewood King Bolete',
  "Berkeley's polypore",
  'Brown puffball',
  'Paltry Puffball',
  'Yellow Stagshorn',
  "St George's Mushroom",
  'Pink Lawn Trich',
  'Giant puffball',
  'Pale Brittlestem',
  'Grayling',
  'Chanterelle',
  'Red Chanterelle',
  'Smooth Chanterelle',
  'Peppery Bolete',
  'The Vomiter',
  'Shaggy Parasol',
  'British Goblet',
  'Mediterranean Pine-Spike',
  'Copper Spike',
  'Caged stinkhorn',
  'Fragrant Funnel Cap',
  'Common Funnel Cap',
  'Twotone Funnel Cap',
  'Clouded Funnel Cap',
  'The Miller',
  'Lentil Shanklet',
  "Tiger's Eye",
  'Clustered Toughshank',
  'Milky Conecap',
  'Fairy Inkcap',
  'Common Ink Cap',
  'Scaly Ink Cap',
  'Shaggy-mane Inky Cap',
  'Silvery Violet Cort',
  'Red-banded Cort',
  'Brown Webcap',
  'Goatcheese webcap',
  'Gypsy Mushroom',
  'Blue-girdled Webcap',
  'Saffron Webcap',
  'Pelargonium Webcap',
  'Woolly Webcap',
  'Apple Webcap',
  'Orange Webcap',
  "Fool's Webcap",
  'Deadly Webcap',
  'Bloodred Webcap',
  'Poison Dye Cort',
  'Pale Bulbous Webcap',
  'Gassy webcap',
  'Violet Cort',
  'Black Trumpet',
  'Trumpet Chantarelle',
  "Fluted Bird's Nest",
  'Earthy Powdercap',
  'Cinnabar Powdercap',
  'Ringless Honey Mushroom',
  'Pale Pinkgill',
  'Silky Pinkgill',
  'Pinkgill mushroom',
  'Scrambled Egg Slime',
  'Deadly Galerina',
  'Dwarf Bell',
  'Rosy earthstar',
  'Slimy Spike',
  'Rosy Spike',
  'Common Rustgill',
  'Bitter Oak-Stump Mushroom',
  'Russet Toughshank',
  'Wood Woollyfoot',
  'False Morel',
  'Hooded false morel',
  'Poison Pie',
  'Veiled Poisonpie',
  'Elastic Saddle',
  'Elfin Saddle',
  "Bear's head",
  'Tiered Tooth',
  "Lion's mane",
  'Ruby Bolete',
  'Bitter Hedgehog',
  'Hedgehog Mushroom',
  'Terracotta Hedgehog',
  'Goblet Waxcap',
  'Butter Waxcap',
  'False Chanterelle',
  'Arched Wood Wax',
  'Late Fall Wax Cap',
  'Olive Wax Cap',
  'Grainy Wax Cap',
  'Conifer Tuft',
  'Sulphur Tuft',
  'Brick Tuft',
  'Snakeskin Brownie',
  'Olive Brownie',
  'Bay Bolete',
  'White Fibrecap',
  'Torn Fibrecap',
  'Conifer Woodtuft',
  'Sheathed Woodtuft',
  'Amethyst Laccaria',
  'Common Laccaria',
  'Weeping Widow',
  'Curry Milkcap',
  'Saffron Milkcap',
  'Orange Milkcap',
  'Poison Lactarius',
  'Indigo Milkcap',
  'Velvet Milkcap',
  'Dark Coconut Milkcap',
  'Pine Milkcap',
  'Rufous Milkcap',
  'Birch Milkcap',
  'Woolly Milkcap',
  'Slimy Lead Lactarius',
  'Ugly Milkcap',
  'Northern Milkcap',
  'Grey Milkcap',
  'Luscious Lactarius',
  'Peppery Milkcap',
  'White-pored Chicken of the Woods',
  'Chicken of the Woods',
  'Orange Oak Bolete',
  'Brown Birch Bolete',
  'Orange Birch Bolete',
  'Shield Dapperling',
  'Stinking Dapperling',
  'Wood Blewit',
  'Flowerpot parasol',
  'White Domecap',
  'Lichen Agaric',
  'Pistle-shaped Puffball',
  'Soft Puffball',
  'Dusky Puffball',
  'Common Puffball',
  'Meadow Puffball',
  'Stump Puffball',
  'Parasol Mushroom',
  'Stinking Parachute',
  'Fairy Ring Marasmius',
  'Collared Parachute',
  'Broad-gilled Collybia',
  'Spring Cavalier',
  'Black Morel',
  'Common Morel',
  "Ravenel's Red Stinkhorn",
  'Yellowleg Bonnet',
  'Common Bonnet',
  'Dark Milking Bonnet',
  'Smooth Mycena',
  'Frost Bonnet',
  'Plumed Bonnet',
  'Poison Radish Ground Mycena',
  'Pink Bonnet',
  'Violet Bonnet',
  'Train Wrecker',
  "Eastern jack-o'lantern",
  "Jack o'Lantern",
  'Lemon-Peel Cup',
  'Brown Mottlegill',
  'Yellow-stained Funnelcap',
  'Umbrella Inky Cap',
  'Poison Pax',
  'Bay Cup',
  'Common Brown Cup',
  'Palomino Cup',
  'Common stinkhorn',
  'Basket stinkhorn',
  "Devil’s Stinkhorn",
  'Woolly Tooth',
  'Alder Scalycap',
  'Golden Scalycap',
  'Sticky Scalycap',
  'Lemon-yellow Pholiota',
  'Dry Scaly Pholiota',
  'Mock Oyster',
  'Trumpet Polypore',
  'Golden oyster mushroom',
  'Oyster mushroom',
  'Indian Oyster',
  'Deer Shield',
  'Ghost Shield',
  'Winter Polypore',
  'Fringed Polypore',
  "Dryad’s Saddle",
  'Dung Roundhead',
  'Tiny Psathyrella',
  'Toothed Jelly Fungus',
  'Ebony Cup',
  'Liberty Cap',
  'Coral fungi',
  'Pale Coral',
  'Pine firefungus',
  'Collared mosscap',
  "Satan's Bolete",
  'Hot Russula',
  'Winecork Brittlegill',
  'Green Brittlegill',
  'Yellow Swamp Brittlegill',
  'Green Crab Russula',
  'Copper Brittlegill',
  'The Sickener',
  'Entire Russula',
  'Russet Brittlegill',
  'Tall Bog Russula',
  'Coral Brittlegill',
  'The Flirt',
  'Darkening Brittlegill',
  'Crab Russula',
  'Scaly Tooth',
  'Scarlet Elfcup',
  'Old Man of the Woods',
  'Spruce Cone Cap',
  'Pine Cone Cap',
  'Verdigris Roundhead',
  'Conifer Roundhead',
  'Wine Cap Stropharia',
  'American slippery Jack',
  'Cow mushroom',
  'Larch Bolete',
  'Slippery Jack Bolete',
  'Variegated Bolete',
  'Velvet Rollrim',
  'Oyster Rollrim',
  'Bitter Yellow Knight',
  'Deceptive Tricholoma',
  'Yellow Knight',
  'Booted Knight',
  'Birch Knight',
  'Matt Knight',
  'Stinking Tricholoma',
  'Bruised Knight',
  'Soapy Knight',
  'Deceiving Knight',
  'Stinking Knight',
  'Ashen Knight',
  'Prunes and Custard',
  'Plums and Custard',
  'Felted Twiglet',
  'Scaly Chanterelle',
  'Bitter Bolete',
  'Red cracking bolete',
  'Yellow-cracking Bolete',
  'Bell Omphalina'
] as const;
